Composite build that causes:
java.lang.AssertionError: Already disposed: Module: 'app'
  at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$throwAlreadyDisposed$1(ComponentManagerImpl.java:248)
  at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
  at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:959)
  at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
  at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
  at com.intellij.openapi.components.impl.ComponentManagerImpl.throwAlreadyDisposed(ComponentManagerImpl.java:246)
  at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:239)
  at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:149)
  at com.intellij.facet.FacetManager.getInstance(FacetManager.java:31)
  at com.android.tools.idea.gradle.project.facet.gradle.GradleFacet.getInstance(GradleFacet.java:57)
  at com.android.tools.idea.gradle.util.GradleUtil.getGradleBuildFile(GradleUtil.java:343)
  at com.android.tools.idea.gradle.project.sync.issues.SyncIssuesReporter.report(SyncIssuesReporter.java:89)
  at com.android.tools.idea.gradle.project.sync.issues.SyncIssuesReporter.report(SyncIssuesReporter.java:66)
  at com.android.tools.idea.gradle.project.sync.idea.data.service.SyncIssueDataService.importData(SyncIssueDataService.java:40)
  at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl.doImportData(ProjectDataManagerImpl.java:294)
  at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl.importData(ProjectDataManagerImpl.java:166)
  at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl.importData(ProjectDataManagerImpl.java:244)
  at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl.importData(ProjectDataManagerImpl.java:251)
  at org.jetbrains.plugins.gradle.service.project.wizard.GradleProjectImportBuilder$1.lambda$onSuccess$1(GradleProjectImportBuilder.java:143)
  at org.jetbrains.plugins.gradle.service.project.wizard.GradleProjectImportBuilder$1.onSuccess(GradleProjectImportBuilder.java:153)
  at com.intellij.openapi.externalSystem.service.project.ExternalProjectRefreshCallback.onSuccess(ExternalProjectRefreshCallback.java:41)
  at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$3.execute(ExternalSystemUtil.java:588)
  at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$5.run(ExternalSystemUtil.java:678)
  at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
  at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
  at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
  at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
  at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
  at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
  at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
  at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)